drop type if exists grocery;
create type grocery as enum (
    'Main',
    'Snack',
    'Lunch',
    'Breakfast'
);

create table if not exists shopping_list (
    id integer primary key generated by default as identity,
    name text,
    price decimal(12,2),
    date_added date default now(),
    checked boolean default false,
    category grocery
);
